
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox2;

	private global::Gtk.Label titulo;

	private global::Gtk.HBox hbox4;

	private global::Gtk.Entry text;

	private global::Gtk.Button Saludar;

	private global::Gtk.HBox hbox5;

	private global::Gtk.Entry entry3;

	private global::Gtk.Button BAleatorio;

	private global::Gtk.Button BSalir;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.titulo = new global::Gtk.Label();
		this.titulo.Name = "titulo";
		this.titulo.LabelProp = global::Mono.Unix.Catalog.GetString("Mi primer programa");
		this.vbox2.Add(this.titulo);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.titulo]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.text = new global::Gtk.Entry();
		this.text.CanFocus = true;
		this.text.Name = "text";
		this.text.IsEditable = true;
		this.text.InvisibleChar = '•';
		this.hbox4.Add(this.text);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.text]));
		w2.Position = 0;
		// Container child hbox4.Gtk.Box+BoxChild
		this.Saludar = new global::Gtk.Button();
		this.Saludar.CanFocus = true;
		this.Saludar.Name = "Saludar";
		this.Saludar.UseUnderline = true;
		this.Saludar.Label = global::Mono.Unix.Catalog.GetString("Saludar");
		this.hbox4.Add(this.Saludar);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.Saludar]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		this.vbox2.Add(this.hbox4);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox4]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.entry3 = new global::Gtk.Entry();
		this.entry3.CanFocus = true;
		this.entry3.Name = "entry3";
		this.entry3.IsEditable = false;
		this.entry3.InvisibleChar = '•';
		this.hbox5.Add(this.entry3);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.entry3]));
		w5.Position = 0;
		// Container child hbox5.Gtk.Box+BoxChild
		this.BAleatorio = new global::Gtk.Button();
		this.BAleatorio.CanFocus = true;
		this.BAleatorio.Name = "BAleatorio";
		this.BAleatorio.UseUnderline = true;
		this.BAleatorio.Label = global::Mono.Unix.Catalog.GetString("Aleatorio");
		this.hbox5.Add(this.BAleatorio);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.BAleatorio]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.BSalir = new global::Gtk.Button();
		this.BSalir.CanFocus = true;
		this.BSalir.Name = "BSalir";
		this.BSalir.UseUnderline = true;
		this.BSalir.Label = global::Mono.Unix.Catalog.GetString("Salir");
		this.hbox5.Add(this.BSalir);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.BSalir]));
		w7.Position = 2;
		w7.Expand = false;
		w7.Fill = false;
		this.vbox2.Add(this.hbox5);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox5]));
		w8.Position = 2;
		w8.Expand = false;
		w8.Fill = false;
		this.Add(this.vbox2);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.Saludar.Clicked += new global::System.EventHandler(this.OnSaludarClicked);
		this.BAleatorio.Clicked += new global::System.EventHandler(this.OnBAleatorioClicked);
		this.BSalir.Clicked += new global::System.EventHandler(this.OnBSalirClicked);
	}
}
